add_movie:
  description: "Add a movie to Radarr"
  fields:
    title:
      description: "Title of the movie"
      example: "Gladiator"

add_tv_show:
  description: "Add a TV show to Sonarr"
  fields:
    title:
      description: "Title of the TV show"
      example: "Breaking Bad"